[package]
name = "homelab-api"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
axum.workspace = true
homelab-api-model = { path = "../../crates/homelab-api-model" }
homelab-core = { path = "../../crates/homelab-core" }
homelab-media = { path = "../../crates/homelab-media" }
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_urlencoded = "0.7"
tokio = { workspace = true, features = ["net", "signal"] }
tower = { workspace = true, features = ["util"] }
tower-http = { workspace = true, features = ["limit", "timeout"] }
tracing.workspace = true

[dev-dependencies]
futures-util = "0.3"
http-body-util = "0.1"
parking_lot = "0.12"
tracing-subscriber.workspace = true
tokio = { workspace = true, features = ["test-util"] }
