[package]
name = "homelab-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "homelab"
path = "src/main.rs"

[dependencies]
chrono.workspace = true
clap = { version = "4.5.51", features = ["derive"] }
homelab-api-model = { path = "../homelab-api-model" }
homelab-client = { path = "../homelab-client" }
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
url = "2.5.7"
uuid = { version = "1.18.1", features = ["v4"] }

[dev-dependencies]
axum.workspace = true
parking_lot = "0.12.5"
tokio = { workspace = true, features = ["net"] }
